	#base_url=https://petstore.swagger.io/v2
	#post_url=base_url + /user
	#get_url=base_url + /user/{username}
	#put_url=base_url + /user/{username}
	#del_url=base_url + /user/{username}
	
	post_url=https://petstore.swagger.io/v2/user
	get_url=https://petstore.swagger.io/v2/user/{username}
	put_url=https://petstore.swagger.io/v2/user/{username}
	del_url=https://petstore.swagger.io/v2/user/{username}